on: [push]
jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hugo
        run: |
          apt update
          apt install -y hugo

      - name: Build
        run: hugo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          - folder: buil